# Generated by Django 5.0.6 on 2024-07-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_terapeuta', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('titulo_profissional', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=100)),
                ('acordo', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('registro_classe', models.CharField(max_length=100)),
                ('conselho_classe', models.CharField(max_length=100)),
                ('dados_bancarios', models.CharField(max_length=100)),
                ('documentos', models.ImageField(blank=True, null=True, upload_to='documentos_terapeuta/')),
                ('outros', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome_terapeuta'],
            },
        ),
    ]
