# Generated by Django 5.0.6 on 2024-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0002_alter_terapeuta_acordo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='metric_terapeuta',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
