# Generated by Django 5.0.6 on 2025-01-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0003_terapeuta_metric_terapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terapeuta',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='terapeuta',
            name='titulo_profissional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
