# Generated by Django 5.0.6 on 2025-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terapeutas', '0004_alter_terapeuta_funcao_alter_terapeuta_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terapeuta',
            name='cor',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
