# Generated by Django 5.0.6 on 2025-01-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_convenio', models.CharField(max_length=100)),
                ('numero_convenio', models.CharField(blank=True, max_length=100, null=True)),
                ('informacoes', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['nome_convenio'],
            },
        ),
    ]
