# Generated by Django 5.0.6 on 2024-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_alter_event_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
