# Generated by Django 5.0.6 on 2024-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_event_confirmado'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='metric_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
