# Generated by Django 5.0.6 on 2025-01-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_event_metric_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='terapeuta',
            field=models.CharField(max_length=100),
        ),
    ]
