# Generated by Django 5.0.6 on 2025-01-15 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0006_alter_event_paciente_alter_event_terapeuta'),
        ('pacientes', '0004_alter_paciente_tipo_convenio'),
        ('terapeutas', '0004_alter_terapeuta_funcao_alter_terapeuta_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paciente', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='event',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terapeuta', to='terapeutas.terapeuta'),
        ),
    ]
