# Generated by Django 5.0.6 on 2025-01-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0009_alter_event_paciente_alter_event_terapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='paciente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='terapeuta',
            field=models.CharField(max_length=100),
        ),
    ]
