# Generated by Django 5.0.6 on 2025-01-16 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0010_alter_event_paciente_alter_event_terapeuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
