# Generated by Django 5.0.6 on 2025-01-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0011_alter_event_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cidade',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='guia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
