# Generated by Django 5.0.6 on 2025-01-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0012_alter_event_cidade_alter_event_guia'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='convenio',
            field=models.CharField(default='convenio', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='cidade',
            field=models.CharField(blank=True, default='Artur Nogueira', max_length=12, null=True),
        ),
    ]
