# Generated by Django 5.0.6 on 2025-01-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0013_event_convenio_alter_event_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cidade',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
