# Generated by Django 5.0.6 on 2025-01-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0014_alter_event_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cor',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
