# Generated by Django 5.0.6 on 2025-01-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0015_event_cor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cor',
        ),
    ]
