# Generated by Django 5.0.6 on 2025-01-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0016_remove_event_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='confirmed_color',
            field=models.CharField(default='', max_length=20),
        ),
    ]
