# Generated by Django 5.0.6 on 2025-01-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0017_event_confirmed_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cidade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
