# Generated by Django 5.0.6 on 2025-04-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0018_alter_event_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes/'),
        ),
        migrations.AddField(
            model_name='event',
            name='foi_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='pagamento_pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
