# Generated by Django 5.0.6 on 2024-07-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('carteirinha', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone_responsavel', models.CharField(max_length=100)),
                ('telefone_contato', models.CharField(max_length=100)),
                ('telefone_emergencia', models.CharField(max_length=100)),
                ('tipo_convenio', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('documento_responsavel', models.CharField(max_length=100)),
                ('foto_carteirinha', models.ImageField(blank=True, null=True, upload_to='documentos_pacientes/')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
