# Generated by Django 5.0.6 on 2024-09-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_carteirinha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='metric_paciente',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
