# Generated by Django 5.0.6 on 2025-01-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_metric_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_convenio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
