# Generated by Django 5.0.6 on 2025-01-18 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nome genérico', max_length=200, null=True)),
                ('title', models.CharField(default='Terapeuta', max_length=200, null=True)),
                ('desc', models.CharField(default='Terapeuta com consultas', max_length=200, null=True)),
                ('profile_img', models.ImageField(blank=True, default='default-user.png', null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
